version: 2

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - testifylint

run:
  tests: false
  timeout: 15m
  concurrency: 15
  relative-path-mode: gomod
  issues-exit-code: 2
  skip-files:
    - "_test\\.go$"

linters:
  default: none
  enable:
    - gocyclo
    - staticcheck
    - govet
    - errcheck
  presets:
    - bugs
    - unused
    - format
  settings:
    gocyclo:
      min-complexity: 15
    errcheck:
      exclude-functions:
        - fmt.Fprintln
        - fmt.Fprint
        - io.Copy
        - (*net/http.ResponseWriter).Write
        - (io.ReadCloser).Close
        - (*net/http.Server).Shutdown
        - (net.Listener).Close
    gosec:
      excludes:
        - G115
